[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
solc = "0.8.28"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
celo_mainnet = "https://forno.celo.org"
celo_sepolia = "https://forno.celo-sepolia.celo-testnet.org"

[etherscan]
celo_mainnet = { key = "${CELOSCAN_API_KEY}", url = "https://api.celoscan.io/api" }
celo_sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
