tunnel: REPLACE_WITH_TUNNEL_UUID
credentials-file: /home/t42/.cloudflared/REPLACE_WITH_TUNNEL_UUID.json

ingress:
  - hostname: graph.example.com
    service: http://localhost:8000
  - service: http_status:404
