[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true

[rpc_endpoints]
megaeth_testnet = "https://carrot.megaeth.com/rpc"
megaeth_frontier = "https://mainnet.megaeth.com/rpc"


[etherscan]
megaeth_testnet = { key = "${MEGAETH_EXPLORER_API_KEY}", url = "https://megaeth-testnet-v2.blockscout.com/api" }
megaeth_frontier = { key = "${MEGAETH_EXPLORER_API_KEY}", url = "https://megaeth.blockscout.com/api" }
